name: flutter_zxing_example
description: Demonstrates how to use the flutter_zxing plugin.
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_zxing: ^2.3.0
  dynamsoft_barcode_reader_bundle_flutter: ^11.4.3000
  dynamsoft_capture_vision_flutter: ^3.4.3000
  scandit_flutter_datacapture_barcode: ^8.5.2
  scandit_flutter_datacapture_core: ^8.5.2
  camera: ">=0.10.5 <0.13.0"
  image_picker: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
